spring:
  application:
    name: votacao-cooperativa
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

user-info:
  base-url: ${USER_INFO_BASE_URL:https://user-info.herokuapp.com}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    com.votacao: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
